name: PHP Compatibility

on: pull_request

jobs:
  php-compatibility:
    name: PHP compatibility
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@daa6e1e0974142ec6d5e39a2f85acb6ab046baf9 # v2.3.1
        with:
          install-deps: yes
          php-version: '8.4'
          tools: composer:v2

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@daa6e1e0974142ec6d5e39a2f85acb6ab046baf9 # v2.3.1
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      # The use of WP-Scripts results in PHP files being generated during the npm build step.
      # In order to ensure PHP Compatibility, the build step must be run in order to ensure all
      # files in the production release of the plugin are compatible with the target PHP versions.
      - name: Build production bundle
        run: npm run build

      # Unzip the newly created zip file to a separate directory.
      - name: Unzip production bundle
        run: |
          mv woocommerce-accommodation-bookings.zip ~
          cd ~
          mkdir prod
          unzip woocommerce-accommodation-bookings.zip -d prod
          cd -

      - name: Copy phpcompat sniffs to production directory
        run: cp phpcs-compat.xml.dist ~/prod/woocommerce-accommodation-bookings/phpcs-compat.xml.dist

      # Installed globally to ensure dev dependencies are not included in compatibility sniffs.
      # At the time of writing no production version of PHPCompatibility/PHP-Compatibility supports
      # PHP 8.4 so a dev version is used in order to ensure the sniffs that have been created are
      # included in the checks.
      - name: Install PHP Compatibility dev-develop globally
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --dev phpcompatibility/php-compatibility:dev-develop#8daeec54772a592ad369be23ae02ed593c71e7f1

      - name: Run PHPCompatibility on all files
        run: |
          cd ~/prod/woocommerce-accommodation-bookings
          ~/.composer/vendor/bin/phpcs . --standard=phpcs-compat.xml.dist -ps --basepath=.
