name: PHP Compatibility

on:
  workflow_call:

jobs:
  php-compatibility:
    name: PHP compatibility
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@b9c1e59aae9fdbe668b068ebd59c1545a88ea9fa # actions-v3.0.5
        with:
          install-deps: yes
          php-version: '8.4'
          tools: composer:v2

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@b9c1e59aae9fdbe668b068ebd59c1545a88ea9fa # actions-v3.0.5
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      - name: Check production PHP compatibility
        run: npm run phpcompat
